### ISSUE TITLE
RecursionError introduced in 0.9.0 in some cases

### ISSUE THREAD

**Issue by CuriousEl3phant502** [mkb79/Audible#235] opened 2023-10-19 23:44 UTC
**Describe the bug**
When using this library sometimes an error occurs: RecursionError: maximum recursion depth exceeded. This does not happen in 0.8.2 only in 0.9.0 and 0.9.1

Example stack trace:     

  File "...\Lib\site-packages\audible\auth.py", line 254, in __len__
    return len(list(self))
               ^^^^^^^^^^
  File "...\Lib\site-packages\audible\auth.py", line 254, in __len__
    return len(list(self))
               ^^^^^^^^^^
  File "...\Lib\site-packages\audible\auth.py", line 254, in __len__
    return len(list(self))
               ^^^^^^^^^^
  [Previous line repeated 992 more times]
RecursionError: maximum recursion depth exceeded

even when setting:
`sys.setrecursionlimit(1500)`
it still encounters the error
**To Reproduce**

Although it can be triggered simply by expanding the object that represents the audible Authenticator object in debug mode in an IDE (that shows all the fields and their values). In some cases expanding the object merely shows a large stack trace like above instead of the fields of the object.

It can even be reproduced by an if check (mostly this in my case and the stacktrace above):

```
auth= <instantiate object>
if auth: -> RecursionError
 ...
```

**Expected behavior**
Not throw a RecursionError as it does not in 0.8.2

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser N/a
- Version 0.9.0
- Python 3.11

**Additional context**
Seems to be the change from:

    def __len__(self):
        return len([i for i in self])

to 

    def __len__(self):
        return len(list(self))

I do not know specifically why though except for the latter is using recursion.

**Comment by mkb79** [comment] 2023-10-20 05:07
@CuriousEl3phant502 
Thank your for your detailed information. This helps me find out the reason very quickly. I could reproduce this error. 

I'm think I've solved this in [this](https://github.com/mkb79/Audible/compare/235-recursionerror-introduced-in-090-in-some-cases) branch. It works for me! Maybe you can test this?

**Comment by CuriousEl3phant502** [comment] 2023-10-20 15:43
@mkb79 thanks for such a quick response. It looks like it's fixed as far as i can tell. I'm no longer able to reproduce this.

Also, one side note, another thing i noticed. For "quality" it looks like the api no longer allows "Extreme" as an option. 
For example, see your example code on line 63
https://github.com/mkb79/Audible/blob/master/examples/download_books_aaxc.py

From what i can tell, if you use anything other than "High" or "Normal" you get `Bad Request (400)`

**Comment by mkb79** [comment] 2023-10-20 16:12
@CuriousEl3phant502 
> Also, one side note, another thing i noticed. For "quality" it looks like the api no longer allows "Extreme" as an option.

Thank you for this information. I'll fix this in the readme!

Can I close this issue now?

**Closed** 2023-10-20 16:13 UTC
